env: "local" # Окружение локалка/remote, dev/prod
storage_path: "./storage/storage.db" # Путь до файла, где хранится база данных
http_server:  #
    address: "localhost:8080"
    timeout: 4s    # Обработка вопроса и ответ клиенту
    iddle_timeout: 60s # Жизненный цикл соединения с клиентом(ждем второго запроса от клиента)